CREATE SCHEMA [NBP]

CREATE TABLE [NBP].[Tables](
	[id] INT PRIMARY KEY IDENTITY(1,1),
	[table] VARCHAR(1) NOT NULL,
	[no] VARCHAR(20) NOT NULL,
	[effectiveDate] DATETIME2 NOT NULL,
	[tradingDate] DATETIME2 NULL
)

CREATE TABLE [NBP].[Rates](
	[id] INT PRIMARY KEY IDENTITY(1,1),
	[tableId] INT NOT NULL,
	[currency] VARCHAR(80) NOT NULL,
	[code] VARCHAR(3) NOT NULL,
	[mid] DECIMAL(8,6) NULL,
	[bid] DECIMAL(8,6) NULL,
	[ask] DECIMAL(8,6) NULL
	FOREIGN KEY ([tableId]) REFERENCES [NBP].[Tables]([Id])
)

GRANT SELECT, INSERT, UPDATE, DELETE ON [NBP].[Tables] TO PUBLIC
GRANT SELECT, INSERT, UPDATE, DELETE ON [NBP].[Rates] TO PUBLIC